import os
import sys
import subprocess
import uuid
import shutil
from fastapi import FastAPI, UploadFile, File, Form, HTTPException, BackgroundTasks
from fastapi.responses import FileResponse
from fastapi.staticfiles import StaticFiles

app = FastAPI(title="Lithophane STL Generator Service")

# Create temporary directory for runs inside the workspace
TEMP_DIR = os.path.join(os.path.dirname(os.path.abspath(__file__)), "temp_runs")
os.makedirs(TEMP_DIR, exist_ok=True)

# Mount the static directory to serve index.html, style.css, app.js
# We check if static directory exists first
STATIC_DIR = os.path.join(os.path.dirname(os.path.abspath(__file__)), "static")
os.makedirs(STATIC_DIR, exist_ok=True)
app.mount("/static", StaticFiles(directory=STATIC_DIR), name="static")


def cleanup_files(*paths):
    """Background task to remove temporary files after the response is sent."""
    for path in paths:
        try:
            if os.path.exists(path):
                os.remove(path)
        except Exception as e:
            print(f"Error during cleanup of {path}: {e}")


@app.get("/")
async def read_index():
    index_path = os.path.join(STATIC_DIR, "index.html")
    if not os.path.exists(index_path):
        raise HTTPException(status_code=404, detail="Frontend index.html not found.")
    return FileResponse(index_path)


@app.post("/api/generate")
async def generate_lithophane(
    background_tasks: BackgroundTasks,
    file: UploadFile = File(...),
    min_thickness: float = Form(0.6),
    max_thickness: float = Form(3.0),
    max_side: float = Form(150.0),
):
    # Validate file type
    if not file.content_type.startswith("image/"):
        raise HTTPException(status_code=400, detail="Uploaded file must be an image.")

    # Generate unique run ID
    run_id = str(uuid.uuid4())
    file_ext = os.path.splitext(file.filename)[1]
    if not file_ext:
        file_ext = ".jpg"  # default fallback

    temp_input_path = os.path.join(TEMP_DIR, f"input_{run_id}{file_ext}")
    temp_output_path = os.path.join(TEMP_DIR, f"output_{run_id}.stl")

    # Save uploaded file
    try:
        with open(temp_input_path, "wb") as buffer:
            shutil.copyfileobj(file.file, buffer)
    except Exception as e:
        cleanup_files(temp_input_path)
        raise HTTPException(status_code=500, detail=f"Failed to save uploaded image: {e}")

    # Build run command
    # Use python executable or just 'python' (it will resolve in virtualenv / docker)
    cmd = [
        sys.executable,
        os.path.join(os.path.dirname(os.path.abspath(__file__)), "main.py"),
        temp_input_path,
        "-o",
        temp_output_path,
        "--min-thickness",
        str(min_thickness),
        "--max-thickness",
        str(max_thickness),
        "--max-side",
        str(max_side),
    ]

    try:
        # Run process
        result = subprocess.run(cmd, capture_output=True, text=True, check=True)
        print(f"Generator stdout:\n{result.stdout}")
    except subprocess.CalledProcessError as e:
        cleanup_files(temp_input_path, temp_output_path)
        raise HTTPException(
            status_code=500,
            detail=f"STL Generation failed.\nError: {e.stderr or e.stdout or str(e)}",
        )
    except Exception as e:
        cleanup_files(temp_input_path, temp_output_path)
        raise HTTPException(status_code=500, detail=f"Failed to run generator: {e}")

    if not os.path.exists(temp_output_path):
        cleanup_files(temp_input_path)
        raise HTTPException(status_code=500, detail="STL file was not generated by the script.")

    # Schedule cleanup of the temp files
    background_tasks.add_task(cleanup_files, temp_input_path, temp_output_path)

    # Return the file as response
    return FileResponse(
        path=temp_output_path,
        media_type="application/octet-stream",
        filename="lithophane.stl",
    )
